apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: break-voting-app
  namespace: default
spec:
  order: 0
  selector: app == 'azure-vote-front'
  serviceAccountSelector: ''
  ingress:
    - action: Deny
      source: {}
      destination: {}
  egress:
    - action: Deny
      source: {}
      destination: {}
  types:
    - Ingress
    - Egress
